### PR TITLE
Small fixes in the subtitle conversion to srt

### PR DESCRIPTION
**Pull request by Paco8**
I noticed two problems with some subtitles. I created a patch to fix them.

The first problem, I found a subtitle which uses two &lt;br /&gt; for a line break. Example:

`<p begin="00:02:27.120" end="00:02:29.440" region="AmazonDefaultRegion" style="AmazonDefaultStyle"><span>Lo he intentando,<br /><br />pero no sé volver.</span></p>
`

When converted to srt there's an empty line between the two lines:

```
00:02:27,120 --> 00:02:29,440
<i>Lo he intentando,

pero no sé volver.</i>
```
Unfortunately when this happens Kodi only displays the first line.

I modified the regular expression to take into account multiple &lt;br /&gt; tags.

The second problem: I found that for some strange reason amazon is using sometimes incorrect characters for some Spanish characters (like using ¨ instead of ¿). I added some code to convert them to the right characters.

### CODE REVIEW

**Comment by Varstahl** [comment]
I would guess they're using a different encoding or failed utf-8 encoding, like they did on the website sometimes. I can't merge it as is 'cause it can break the other locales I need to do some proper adjustments. It would help a lot if you could provide a link to the original SRT.

**Comment by Paco8** [comment]
This one uses the wrong characters for ¿ and ¡

https://dmqdd6hw24ucf.cloudfront.net/9aed/dfa2/6e2f/42d1-921d-88cb2023662c/1742b097-68c2-46ed-b947-67df290db9c4.ttml2

**Comment by Varstahl** [comment]
```
12
00:01:55,157 --> 00:01:58,786
Estoy enganchada a ti
¨No sabes que eres tóxico?

<p begin="00:01:55.157" end="00:01:58.786" region="AmazonDefaultRegion" style="AmazonDefaultStyle">
  <span>Estoy enganchada a ti<br />¨No sabes que eres tóxico?</span>
</p>
```

Both the SRT and the TTML2 are incorrect.

**Comment by Varstahl** [comment]
@Paco8 if you watch it on primevideo.com, does it show the correct characters?

**Comment by Paco8** [comment]
It turns out that if I play the movie in the PC with a web browser from primevideo.com, it doesn't show the Spanish subtitles at all, a popup appears saying that it couldn't display the subtitles.
If I play it on a smartphone with the official app, the subtitles are shown but using with the incorrect characters.

I noticed this problem in 4 or 5 movies so far.

**Comment by Varstahl** [comment]
Haven't had the time to check on the source of their errors, but this looks fair enough, I'll merge it in.

**Pull request merged**
