### PR TITLE
PrimeVideo support for Amazon VOD

### LINKED ISSUE #66: Error when trying to log in
Hello,
I get the following error on Kodi when trying to enter my credentials. It lets me enter my email address and my password, I then get "Unknown Error, please enable advanced debugging in settings and check avod-login.log/avod-login-si.log/avod-login-mfa.log"
How can I solve this?
Many thanks!

### PR DESCRIPTION
**Pull request by Varstahl**
You already know of the work I was doing as per #22, so I'll keep it concise (famous last words).

In order to avoid causing problems to the other services, I tried to build self-contained functions and reuse your code as much as possible. The functions that introduce necessary parts all start with `PrimeVideo_`:

* **BuildRoot**: builds the home menu;
* **Browse**: the main browsing/playback manager, builds ad-hoc lists;
* **LazyLoad**: the (messy) scraper. Handles all the JSON-AmazonUI-Streaming, JSON and HTML data provided by amazon and turns them into usable data;
* **Search**: provides PV search functionalities;
* **GPRV**: (Get prime video values) since I needed to call `getUrldata` inside `LazyLoad` for additional parsing, I extracted the needed bits into its own dedicated function and left only the call inside `IStreamPlayback`.

There are some limitations at the moment:

* the user can't decide if they want additional data or not (runtime, actors, directors, fanart, and so on). There was some debate, but since I needed to force the additional downloads on the series list that amazon kept breaking, I enabled them for about everything and ran with it. You can pinpoint the locations by searching `getUrldata` calls inside `PrimeVideo_LazyLoad`;
* watchlist, favourites, notifications to amazon about what is being watched, and "Set as watched/unwatched" are not available yet;
* extra data download from external sites is currently disabled for PV;
* there is no manual way to refresh a portion of the catalog (sub)tree;
* I didn't check if there is the possibility to register `Amazon VOD` as a device in the amazon settings. In theory it should provide different suggestions based on the device the call comes from, but I'm not even sure that works;
* age restriction not implemented. Legal age change based on the country, and I don't know if those settings are worldwide or market or country defined, requires proper investigation.

The PV catalog is lazily scraped on the user request, grown inside a dict/SortedDict, and saved/loaded through pickle. It currently auto destructs every 11 hours.

The build has been tested from Italy on Win7 and Debian Jessie. Some users reported it as working on LibreElec, but I didn't personally test it.

## What differs that isn't strictly related to PV

For different reasons I modified parts of your code or your file structure where I felt the need to. I'll try to recap, in no particular order:

* **Localization files upgraded to the newest filename format**: changed from the old, no longer supported, `resources/language/<language_name>/strings.po` to the newer `resources/language/resource.language.<locale>/strings.po`. Since the addon is now open to a plethora of countries, this will help future localization with proper locale, for example Portuguese (pt_PT) and Brazilian Portuguese (pt_BR);
* **Removed urllib2 in favour of Requests**: aside the little problems with urllib2, the PV scraping requires a lot of calls, since amazon disabled all the previous batch API endpoints. I built a tiny modification and now supports Keep-Alive and connection pooling. It also builds as many session as needed. While modifying it I also fixed a potential big problem in the `getURL` function, where Host was not set based on the request URL but based on the `BaseUrl`. That was making all calls to every extern provider using `Host: primevideo.com/amazon.tld` in the headers;
* **Removed LWPCookieJar in favour of Requests'**: this comes as a fix for different distributions, and should fix #66. Cookie management could be slightly improved considering that now sessions are per script execution, thus removing a lot of cookie loading clutter, but in order to change as little code as possible I refrained from optimizing any further. Since Requests cookie jar is pickleable, I've used that method to save/load;
* **Changed the no mode to `None` instead of empty string**: it seemed a better idea that also required less comparisons;
* **Added a `Remember Me` option**: even though the cookies were set to ignore expiration date, sessions are wiped server side and required relog quite often. I've added an option in the settings, enabled by default, allowing ticking the `Remember Me` checkbox. This should work on all `amazon.<tld>`.

## What works

PV scraping, metadata, multi-language streams playback with subtitles, widevine decoding. Possibly now login working where previously resulting in cookie error.

## What I forgot

~Since the removal of urllib2, the lines 168 and 169 that disable SSL verification are now useless, together with the `import ssl`.~ Fixed in e7a4bd7032fe9611f820bfbd6dc6ac76a695822e

## Conclusions

I intentionally avoided to alter most of the meta-files, like the readme or the addon.xml (although I introduced the requests dependency, even if it was unnecessary given that it's already an `inputstreamhelper` dependency). I wrote a couple [wiki pages](https://github.com/Varstahl/xbmc/wiki) to help the users navigate through my nightly builds, feel free to reuse whatever you need. The following are the two images in the main page:

```
![new primevideo option](https://user-images.githubusercontent.com/284077/35077646-a1e7edcc-fbfe-11e7-99c2-1fefea338229.jpg)
![Extract the MarketplaceID via browser](https://user-images.githubusercontent.com/284077/35473262-d25b53c8-037d-11e8-8759-858eaa26c2f2.jpg)
```

This should be all, unless I forgot something, but feel free to ask.

### CODE REVIEW

**Comment by Sandmann79** [comment]
Hi i just began to inspect your code and see that we don't need the GPRV/getflashVars methods anymore? The only needed var is asin and thats where this methods called with. All other vars like marketid, deviceid are already defined by global vars and devicetypeid can be hardcoded in geturldata. 
Customerid and token are not needed anymore since last december, since that time the getplaybackressources request requires an cookie.

**Comment by Varstahl** [comment]
Ah yes, wasn't aware of that. Since I couldn't really test the various amazon.tld (or at least I thought I couldn't), I just kept everything intact. If you say that all the various flashVars are not required anymore I can refactor that code. I'll do it after work.

**Comment by Sandmann79** [comment]
It's not necessary, i'am merging the pm, do some pep8 formatting and remove the methods.

**Comment by Sandmann79** [comment]
@Varstahl Btw i've send you an invite to access this repo, so you can directly commit any changes.

**Pull request merged**
