### PR TITLE
[Amazon VOD] Fix: Hide pay entries in watchlist if payCont isn't set

### PR DESCRIPTION
**Pull request by TehTux**
This patch hides paid content in the watchlist if the option is set in the settings.

### CODE REVIEW

**Comment by dynamiik** [comment]
This does not work for me. It is still shown in orange colour. I have Amazon VOD 0.6.9

**Comment by TehTux** [comment]
> This does not work for me. It is still shown in orange colour. I have Amazon VOD 0.6.9

It can't work if you are using 0.6.9... 🙈

**Comment by Varstahl** [comment]
While I'm sure that works, isn't it the wrong place to do it? Everything should be scraped, _and then_ hidden if the option is checked. Which would then beg the question, "why isn't it filtered already upon displaying"?

Also, as far as I can tell, this would also prevent scraping for every other pay entries in the library.

I can't merge this as-is, and being unable to test it myself we need @Sandmann79 to review this PR.

**Comment by TehTux** [comment]
> Everything should be scraped, _and then_ hidden if the option is checked. 
Why should everything be scraped? It is loading time after all...

> Also, as far as I can tell, this would also prevent scraping for every other pay entries in the library.
That could be. But why do you need paid content in the library when you have turned it off? I'm not using the library function, so it's hard for me to judge.

Sandman please enlighten us! 😄

**Comment by Varstahl** [comment]
I believe the rationale was to avoid multiple (lengthy) scraping each time the option is turned on/off and/or inconsistencies with entries being included or removed with prime. I'm the dev responsible for PrimeVideo.com support and general maintenance, so I'm not entirely sure of the reasoning behind the design choices in regard to amazon.TLDs.

What I **do** know, is that I would have done the same, so there's that.

**Comment by TehTux** [comment]
You are right. It's the wrong place. If "Display TV-Show instead of Seasons in Watchlist" is enabled, it doesn't work... I will check it again...

**Comment by TehTux** [comment]
> If "Display TV-Show instead of Seasons in Watchlist" is enabled, it doesn't work... 

That's fixed now. But there is still the problem with the library... I will try to fix this.

**Pull request closed without merging**
