### PR TITLE
Fixed multiuser support for PrimeVideo

### PR DESCRIPTION
**Pull request by Varstahl**
Since it doesn't really make much sense introducing the user change in the cache, I've slightly modified the way the catalog is rebuilt and updated.

* **Change the string 30134 into `Current User: {0}`**: format instead of concatenation gives better results when localizing the addon. Maybe not in this case but there might be other times where the translator might need to invert the order of parameters, and if you go with concatenation that won't work.
* **Introduced a `countUsers` function**: avoids the need of `loadUsers` if you're in need of knowing how many users are available at any given time, also because loadUsers crashes horribly if the file doesn't exist.
* **Slightly changed `switchUser`**: it now only changes the user if the selected user isn't the currently active one (we might want to remove the current user from the selection maybe). Also it now returns a boolean for more granular controls: true if a user was selected, not currently active, and switched; false otherwise.

Through the introduction of `countUsers` and the slight change of `switchUser` we are now also able to hide (at least in the PV for the moment) the current user if there aren't at least 2. Doesn't make much sense to pop up a dialog when there's nothing to do.

### CODE REVIEW

**Comment by Varstahl** [comment]
Hold it for the moment, there's a weird bug in the login that stalls and crashes kodi, I'm trying to pinpoint the causes.

**Comment by Varstahl** [comment]
@Sandmann79 bug introduced in 38e0b431364632ae73d4087ce4607580e68655c6, [line 2270](https://github.com/Sandmann79/xbmc/commit/38e0b431364632ae73d4087ce4607580e68655c6#diff-61ba02e2d92b786cc74537fe5b16294bR2270), the same line that was causing me troubles stalling during multi-user counting.

After the credentials are required, `LogIn` calls `loadUser`, which calls `loadUsers`, which fails when there is no `account.lst`, which in turns refreshes the page, at which point we're back into `LogIn`, which continues the endless loop.

As a bandaid fix (6a3ca96fbe2271d14c2c9f0267326fd48c835fdb) I'm removing the refresh inside `loadUsers`, since about every function that calls `loadUsers` (except for `loadUser`) already contains a `Container.Refresh` where needed.

**Comment by Sandmann79** [comment]
At this point we don't need the `countUser` anymore. You can also call `len(loadUsers())` instead. The crash was only the result of the container refresh.
A small cosmetic thing - we should do a refresh after deleting the current user below line [2249](https://github.com/Varstahl/xbmc/blob/6a3ca96fbe2271d14c2c9f0267326fd48c835fdb/plugin.video.amazon-test/default.py#L2349). So its display no user, if switch user is cancelled.
With all other changes i totally agree.

**Comment by Sandmann79** [comment]
Another small thing, after you created directly the directoryitem for switch user, you can also add the context menu items (add,delete,rename) for that, like in AV main menu. It would be nice.

**Comment by Varstahl** [comment]
Agree to both, will do it shortly.

**Comment by Sandmann79** [comment]
On this way, can you add the `{0}` to de_de language, too?

Short question about git handling:
Did you know how to add commits to an incoming PR without creating an separate branch or clone your repo?
I'm not so familiar with git at this point.

**Comment by Varstahl** [comment]
> On this way, can you add the {0} to de_de language, too?

If you mean the part where it uses the 30134 string, it's [already done](https://github.com/Sandmann79/xbmc/pull/74/commits/384e7f063428f23cea284da47911b77e70fbe44b#diff-61ba02e2d92b786cc74537fe5b16294bR373)

About the PR, I'll admit I learnt by doing it, these are the first two PRs of my life, I'm generally on the project manager side of things. Anyway in order to include more commits, you just push to the same branch you're trying to merge. So in this case the `origin/master` of my branch.

If you were asking how you can add commits to this current PR, you should push it to my fork, but since it's my personal one it doesn't make much sense. I think you can still push to your master though, and then merge it later.

**Comment by Varstahl** [comment]
Done. I wrapped the contextual menu in a function, so as not to pollute the global namespace creating objects we don't need.

While at it, I noticed that there still were several `...` in the strings.po, replaced them with proper ellipses `…` and changed the code to match the new style.

**Comment by Sandmann79** [comment]
> If you mean the part where it uses the 30134 string, it's already 
>
No i meant the /resources/language/resource.language.de_de/strings.po file

>...my personal one it doesn't make much sense...
>
But in this case i have to checkout the complete repo, to get the PR commits or create a new branch based on your master. 
Maybe the best way ist to create a local branch for the PR and add some commits and push it to your master.
It should work, because on Github PR Page there is a small note:
`Add more commits by pushing to the master branch on Varstahl/xbmc.`

>While at it, I noticed that there still were several ... in the strings.po, replaced them with proper ellipses … and changed the code to match the new style.
>
What you mean with that? You replaced three dots with a one character containing three dots?

**Comment by Varstahl** [comment]
> No i meant the /resources/language/resource.language.de_de/strings.po file

Ah sorry, I completely missed the point, I'll do it right away.

> What you mean with that? You replaced three dots with a one character containing three dots?

Pretty much, yes. There is a character for the ellipsis, which is the triple dot character. I've worked with tons of books in the past years (and still am), so it came natural :D
I forgot to update the other strings.po though, I'll do it too right away.

> Maybe the best way is to create a local branch for the PR and add some commits and push it to your master.

We can close this PR, you can work with remote branches and PR onto mine, it's no big deal.

**Comment by Varstahl** [comment]
Short example, from inside your working directory:

```
git remote add upstream https://github.com/Varstahl/xbmc.git
git fetch upstream
```
At that moment you will have 2 separate local branches (on your PC), the `origin` (yours) and the `upstream` (mine). So you can `git checkout <origin/upstream>` and work on my version or yours. Suppose you want to PR on my current branch, you can `git checkout upstream`, `git pull`, work on it and then PR on my repo.

**Comment by Sandmann79** [comment]
Tanks for the info, next time i try it.

**Comment by Varstahl** [comment]
I've corrected the other strings.po.

I'm sorry but working with books so much made me kind of allergic to this sort of things. Another thing I wanted desperately to change is the &lt;space&gt;-&lt;space&gt; (` - `) to a medium dash ` – ` (Alt+0150), but I'm not doing it. I'm sorry, it's professional bias, I just can't help it :D

**Comment by Varstahl** [comment]
Contrary to what I stated in the previous comment I couldn't help myself and just did it. Now, at least on primevideo, titles such as `TV Series - Anime` will now be correctly displayed as `TV Series – Anime`. It makes my soul soooo much lighter.

I didn't apply the same thing to amazon.tld functions because:

1. I don't know if you want to do it the same way I used it at the moment;
2. since you introduced titles like `--=` it will cause graphical differences.

I'll let you be the judge of that. For the time being I'm happy to see that titles from the primevideo catalog are now finally displayed correctly.

**Comment by CGarces** [comment]
@Sandmann79 Just a note about the PR and Github.
If is a minor change you can made changes using the GUI. You can made changes directly over the branch used by the PR (in this case `Varstahl:master`) if the check "Allow edits from maintainers" is check.

See:
https://github.com/blog/2247-improving-collaboration-with-forks
https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

This feature + the ability to Squash commits from PR made very easy made trivial changes without wait for the original autor or the PR.

https://help.github.com/articles/merging-a-pull-request/

IMO each PR must use a specific branch, to not mix changes from different functionalities, and allow work in multiple modifications at the same time.

**Comment by Varstahl** [comment]
There seems to be a bug regression in some kind of formatted titles, I'm not sure what started causing it again, I'll check tomorrow.

Btw we should probably create a branch for the 0.5.0 release instead of merging on the master, the changes keep piling up.

**Comment by Sandmann79** [comment]
I don't think that's necessary at this point. Maybe one or two changes and we should release the new version. 
Maybe you disable the formatting for now and include this at next version?

**Comment by Varstahl** [comment]
I don't think it's from the formatting, but I'm checking now. Either amazon changed something or there is a problem somewhere that I didn't find before and I just happened to see last night.

**Comment by Varstahl** [comment]
puah

Well, Amazon, I'll be damned…

**Comment by Sandmann79** [comment]
Ah some Unicode formatting problems. That's bad.

**Comment by Varstahl** [comment]
That's an error on amazon's side, I'm not sure we can fix that. I'm thinking on a way to detect if amazon fucked up the encoding, but I'm not sure it's possible.

**Comment by Varstahl** [comment]
In theory is as simple as `.encode('latin-1').decode('utf-8')`, the question is how to avoid errors…

**Comment by Varstahl** [comment]
Looks good to go, imo.

**Pull request merged**
